name: "plan"
on:
  push:
    branches:
      - "main"
jobs:
  get_plan:
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.plan.outputs.plan }}
    steps:
      - uses: actions/checkout@v3
      - id: plan
        run: echo "::setOutput plan::workflow-test-child"
  run-release:
    uses: kjuulh/${{ needs.get_plan.outputs.plan }}/.github/workflows/ci.yml@main
